# Generated by Django 4.2.7 on 2023-11-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=50, verbose_name='Document Title')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('social1', models.URLField(verbose_name='Social 1')),
                ('social2', models.URLField(verbose_name='Social 2')),
                ('social3', models.URLField(verbose_name='Social 3')),
                ('social4', models.URLField(verbose_name='Social 4')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('paht1', models.CharField(max_length=30, verbose_name='Path 1')),
                ('paht2', models.CharField(max_length=30, verbose_name='Path 2')),
                ('paht3', models.CharField(max_length=30, verbose_name='Path 3')),
                ('paht4', models.CharField(max_length=30, verbose_name='Path 4')),
                ('paht5', models.CharField(max_length=30, verbose_name='Path 5')),
                ('paht6', models.CharField(max_length=30, verbose_name='Path 6')),
                ('paht7', models.CharField(max_length=30, verbose_name='Path 7')),
            ],
        ),
    ]
