# Generated by Django 4.2.7 on 2023-11-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Header'},
        ),
    ]
