# Generated by Django 4.2.7 on 2023-11-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_header_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='', verbose_name='Background')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('colored_title', models.CharField(max_length=20, verbose_name='Colored Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('button1', models.CharField(max_length=30, verbose_name='Button 1')),
                ('button2', models.CharField(max_length=30, verbose_name='Button 2')),
                ('video_url', models.URLField(verbose_name='Video Url')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
    ]
