# Generated by Django 4.2.7 on 2023-11-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20, verbose_name='Icon')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Featured Services',
                'verbose_name_plural': 'Featured Services',
            },
        ),
    ]
