# Generated by Django 4.2.7 on 2023-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_featuredservices_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button1', models.CharField(max_length=30, verbose_name='About Button')),
                ('title1', models.CharField(max_length=40, verbose_name='About Title')),
                ('colored_title1', models.CharField(max_length=40, verbose_name='About Colored Title')),
                ('text1', models.TextField(verbose_name='About Text')),
                ('button2', models.CharField(max_length=30, verbose_name='Services Button')),
                ('title2', models.CharField(max_length=40, verbose_name='Services Title')),
                ('colored_title2', models.CharField(max_length=40, verbose_name='Services Colored Title')),
                ('text2', models.TextField(verbose_name='Services Text')),
                ('button3', models.CharField(max_length=30, verbose_name='Portfolio Button')),
                ('title3', models.CharField(max_length=40, verbose_name='Portfolio Title')),
                ('colored_title3', models.CharField(max_length=40, verbose_name='Portfolio Colored Title')),
                ('text3', models.TextField(verbose_name='Portfolio Text')),
                ('button4', models.CharField(max_length=30, verbose_name='Team Button')),
                ('title4', models.CharField(max_length=40, verbose_name='Team Title')),
                ('colored_title4', models.CharField(max_length=40, verbose_name='Team Colored Title')),
                ('text4', models.TextField(verbose_name='Team Text')),
                ('button5', models.CharField(max_length=30, verbose_name='Pricing Button')),
                ('title5', models.CharField(max_length=40, verbose_name='Pricing Title')),
                ('colored_title5', models.CharField(max_length=40, verbose_name='Pricing Colored Title')),
                ('text5', models.TextField(verbose_name='Pricing Text')),
                ('button6', models.CharField(max_length=30, verbose_name='FAQ Button')),
                ('title6', models.CharField(max_length=40, verbose_name='FAQ Title')),
                ('colored_title6', models.CharField(max_length=40, verbose_name='FAQ Colored Title')),
                ('text6', models.TextField(verbose_name='FAQ Text')),
                ('button7', models.CharField(max_length=30, verbose_name='Contact Button')),
                ('title7', models.CharField(blank=True, max_length=40, verbose_name='Contact Title')),
                ('colored_title7', models.CharField(max_length=40, verbose_name='Contact Colored Title')),
                ('text7', models.TextField(verbose_name='Contact Text')),
            ],
        ),
    ]
