# Generated by Django 4.2.7 on 2023-11-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30, verbose_name='Skill')),
                ('procent', models.IntegerField(verbose_name='Procent')),
            ],
        ),
    ]
