# Generated by Django 4.2.7 on 2023-11-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=40, verbose_name='Icon')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
    ]
