# Generated by Django 4.2.7 on 2023-11-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('offers', models.TextField(verbose_name='Offers')),
                ('button', models.CharField(max_length=30, verbose_name='Button Name')),
                ('advanced', models.BooleanField(blank=True, verbose_name='Advanced')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricing',
            },
        ),
    ]
