# Generated by Django 4.2.7 on 2023-11-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_faq_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=40, verbose_name='Icon')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('info', models.CharField(max_length=100, verbose_name='Info')),
            ],
        ),
    ]
