# Generated by Django 4.2.7 on 2023-11-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_map', models.TextField(verbose_name='Google Map')),
                ('placeholder1', models.CharField(max_length=50, verbose_name='Placeholder 1')),
                ('placeholder2', models.CharField(max_length=50, verbose_name='Placeholder 2')),
                ('placeholder3', models.CharField(max_length=50, verbose_name='Placeholder 3')),
                ('placeholder4', models.CharField(max_length=50, verbose_name='Placeholder 4')),
                ('button1', models.CharField(max_length=30, verbose_name='Button 1')),
                ('title', models.CharField(max_length=50, verbose_name='Newsletter Title')),
                ('text', models.TextField(verbose_name='Newsletter Text')),
                ('placeholder5', models.CharField(max_length=50, verbose_name='Placeholder 5')),
                ('button2', models.CharField(max_length=30, verbose_name='Button 2')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
    ]
